### ISSUE TITLE
Error in Surprise Command

### ISSUE THREAD

**Issue by umutphp** [umutphp/awesome-cli#20]
**Describe the bug**
Surprise command sometimes throws error.

```bash
$ awesome-cli surprise
awesome-cli Version 0.7.1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x768c0d]

goroutine 1 [running]:
github.com/umutphp/awesome-cli/internal/package/node.(*Node).GetName(...)
        /home/runner/work/awesome-cli/awesome-cli/internal/package/node/node.go:30
github.com/umutphp/awesome-cli/internal/package/prompter.ToFavouriteString(0x0, 0x0, 0x0)
        /home/runner/work/awesome-cli/awesome-cli/internal/package/prompter/prompter.go:50 +0xbd
github.com/umutphp/awesome-cli/internal/package/prompter.Surprise(0xc000215dd0, 0xc0002065c0, 0x15, 0x0, 0x0, 0x1a, 0x20, 0xc0000e5da0, 0x47831c, 0xde8580)
        /home/runner/work/awesome-cli/awesome-cli/internal/package/prompter/prompter.go:61 +0x13a
main.SurpriseRepo(0xc0000f6370, 0xc0000f6370, 0xe10928, 0x0, 0x0, 0xe10928, 0x0, 0x0)
        /home/runner/work/awesome-cli/awesome-cli/main.go:69 +0xee
main.Argumented(0xc0000be030, 0x1, 0x1, 0xc0000f6370, 0xc0000f6370, 0xe10928, 0x0, 0x0, 0xe10928, 0x0, ...)
        /home/runner/work/awesome-cli/awesome-cli/main.go:130 +0x29e
main.main()
        /home/runner/work/awesome-cli/awesome-cli/main.go:32 +0x1d4

```

**To Reproduce**
Execute `awesome-cli surprise` to reproduce the error. You may have to execute many times to generate the error.

**Comment by umutphp** [comment]
If you run the command with "surprise" before running any other parameter, this error occurs. I am closing it for now.
